#!/bin/sh
VAR="FISN_Staging:123456"
OLDIFS=$IFS
IFS=":"
set -- $VAR
PROJECT=$1
VERSION_DATE=$(TZ=":America/New_York" date +%Y%m%d_Build%H%M)
PREFIX=""
case "$PROJECT" in
        *_Staging)
                PREFIX="rc"
                ;;

        *_Production)
                PREFIX="v"
                ;;
esac

export USE_VERSION="$PREFIX$VERSION_DATE"
IFS=$OLDIFS
