#!/bin/sh
VAR="${CODEBUILD_BUILD_ID}"
OLDIFS=$IFS
IFS=":"
set -- $VAR
PROJECT=$1
VERSION_DATE=":US/Eastern" date +%Y%m%d_Build%H%M
PREFIX=""
case $PROJECT in
	FISN_Staging)
		PREFIX="rc"
		;;

	FISN_Production)
		PREFIX="v"
		;;
esac

export USE_VERSION="$PREFIX$VERSION_DATE"
IFS=$OLDIFS
